<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>gentoo@houseofsuns.org</email>
		<name>Markus Walter</name>
	</maintainer>
	<longdescription># Lago Python ClientThis is a python wrapper for Lago API[![PyPI version](https://badge.fury.io/py/lago-python-client.svg)](https://badge.fury.io/py/lago-python-client)[![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)](https://spdx.org/licenses/MIT.html)## InstallationInstall the lago-python-client via pip from PyPI:    $ python -m pip install &quot;lago-python-client&quot;(Alternative) Install the lago-python-client via [poetry](https://python-poetry.org/) from PyPI:    $ poetry add &quot;lago-python-client&quot;## UsageCheck the [lago API reference](https://doc.getlago.com/docs/api/intro)## Development### Install the dependencies```bashpython -m pip install --upgrade pip setuptools wheelpython -m pip install .[test]```### Run tests```bashpytest```## DocumentationThe Lago documentation is available at [doc.getlago.com](https://doc.getlago.com/docs/api/intro).## Changelog* [#55](https://github.com/getlago/lago-python-client/pull/55) -- Error handling (`LagoApiError`)Example, creating wallet:```try:    response = client.wallets().create(wallet)except LagoApiError as error:    do_something(status=error.status_code)```### Available properties:```&gt;&gt;&gt; error.status_code422&gt;&gt;&gt; error.detail'Unprocessable Entity'&gt;&gt;&gt; error.headers{'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '0', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Permitted-Cross-Domain-Policies': 'none', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-cache', 'X-Request-Id': '613e7542-b29e-4224-bd19-a16dd1bfa62b', 'X-Runtime': '1.024304', 'Vary': 'Origin', 'Transfer-Encoding': 'chunked'}&gt;&gt;&gt; error.response{'status': 422, 'error': 'Unprocessable Entity', 'code': 'validation_errors', 'error_details': {'customer': ['wallet_already_exists']}}&gt;&gt;&gt; error.response['error_details']['customer'][0]'wallet_already_exists'&gt;&gt;&gt; error.url'http://localhost:3000/api/v1/wallets'```## ContributingThe contribution documentation is available [here](https://github.com/getlago/lago-python-client/blob/main/CONTRIBUTING.md)## LicenseLago Python client is distributed under [MIT license](LICENSE).</longdescription>
</pkgmetadata>