# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="django-error-reporting"
REALVERSION="0.9"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="DataDog and Sentry error reporting for Django"

HOMEPAGE="https://github.com/Lenders-Cooperative/django-error-reporting"
LICENSE=""
SRC_URI="https://files.pythonhosted.org/packages/source/d/${REALNAME}/${REALNAME}-${REALVERSION}.tar.gz"
SOURCEFILE="${REALNAME}-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE=""
DEPENDENCIES="dev-python/django[${PYTHON_USEDEP}]
	dev-python/sentry-sdk[${PYTHON_USEDEP}]
	dev-python/ddtrace[${PYTHON_USEDEP}]
	dev-python/django-datadog-logger[${PYTHON_USEDEP}]"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
