<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>gentoo@houseofsuns.org</email>
		<name>Markus Walter</name>
	</maintainer>
	<longdescription>==============better_exchook==============A nicer drop-in-replacement for Python ``sys.excepthook``,i.e. it prints stack traces with extended information.It will add some useful information for each frame,like printing the relevant variables (relevant = referenced in the code line).Also see `Python source and comments &lt;https://github.com/albertz/py_better_exchook/blob/master/better_exchook.py&gt;`_ for further details.Features--------* Shows locals/globals per frame, but only those used in the current statement.  It does this by a simple Python code parser.* Multi-line Python statements in the stack trace output,  in case the statement goes over multiple lines.* Shows full function qualified name (not just ``co_name``).* Colored/formatted output of each frame.* Syntax highlighting for the Python source code.* Support for `DomTerm &lt;https://github.com/PerBothner/DomTerm&gt;`__,  where it folds all the details of each stack frame away by default,  and thus provides a much more comprehensive overview,  while still providing all the details when needed... image:: https://github.com/albertz/py_better_exchook/workflows/CI/badge.svg    :target: https://github.com/albertz/py_better_exchook/actionsInstallation------------You can just copy over the single file ``better_exchook.py`` to your project.Or alternatively, it is also available `on PyPI &lt;https://pypi.python.org/pypi/better_exchook&gt;`_and can be installed via:.. code::  pip install better_exchookUsage-----.. code:: python  import better_exchook  better_exchook.install()  # will just do: sys.excepthook = better_exchookExamples--------Python example code:.. code:: python    try:        x = {1:2, &quot;a&quot;:&quot;b&quot;}        def f():            y = &quot;foo&quot;            x, 42, sys.stdin.__class__, sys.exc_info, y, z        f()    except Exception:        better_exchook.better_exchook(*sys.exc_info())Output:.. code::  EXCEPTION  Traceback (most recent call last):    File &quot;better_exchook.py&quot;, line 478, in &lt;module&gt;      line: f()      locals:        f = &lt;local&gt; &lt;function f at 0x107f1de60&gt;    File &quot;better_exchook.py&quot;, line 477, in f      line: x, 42, sys.stdin.__class__, sys.exc_info, y, z      locals:        x = &lt;global&gt; {'a': 'b', 1: 2}        sys = &lt;global&gt; &lt;module 'sys' (built-in)&gt;        sys.stdin = &lt;global&gt; &lt;open file '&lt;stdin&gt;', mode 'r' at 0x107d9f0c0&gt;        sys.stdin.__class__ = &lt;global&gt; &lt;type 'file'&gt;        sys.exc_info = &lt;global&gt; &lt;built-in function exc_info&gt;        y = &lt;local&gt; 'foo'        z = &lt;not found&gt;  NameError: global name 'z' is not definedPython example code:.. code:: python    try:        f = lambda x: None        f(x, y)    except Exception:        better_exchook.better_exchook(*sys.exc_info())Output:.. code::  EXCEPTION  Traceback (most recent call last):    File &quot;better_exchook.py&quot;, line 484, in &lt;module&gt;      line: f(x, y)      locals:        f = &lt;local&gt; &lt;function &lt;lambda&gt; at 0x107f1df50&gt;        x = &lt;local&gt; {'a': 'b', 1: 2}        y = &lt;not found&gt;  NameError: name 'y' is not definedPython example code:.. code:: python    try:        (lambda x: None)(__name__,                         42)  # multiline    except Exception:        better_exchook.better_exchook(*sys.exc_info())Output:.. code::  EXCEPTION  Traceback (most recent call last):    File &quot;better_exchook.py&quot;, line 490, in &lt;module&gt;      line: (lambda x: None)(__name__,                             42)  # multiline      locals:        x = &lt;local&gt; {'a': 'b', 1: 2}        __name__ = &lt;local&gt; '__main__', len = 8  TypeError: &lt;lambda&gt;() takes exactly 1 argument (2 given)Python example code:.. code:: python    # use this to overwrite the global exception handler    sys.excepthook = better_exchook.better_exchook    # and fail    finalfail(sys)Output:.. code::  EXCEPTION  Traceback (most recent call last):    File &quot;better_exchook.py&quot;, line 497, in &lt;module&gt;      line: finalfail(sys)      locals:        finalfail = &lt;not found&gt;        sys = &lt;local&gt; &lt;module 'sys' (built-in)&gt;  NameError: name 'finalfail' is not definedScreenshot:.. image:: https://gist.githubusercontent.com/albertz/a4ce78e5ccd037041638777f10b10327/raw/7ec2bb7079dbd56119d498f20905404cb2d812c0/screenshot1.pngScreencast with `DomTerm &lt;http://domterm.org&gt;`__:.. image:: https://gist.githubusercontent.com/albertz/a4ce78e5ccd037041638777f10b10327/raw/7ec2bb7079dbd56119d498f20905404cb2d812c0/screencast-domterm.gifSimilar projects----------------* `Nose does something similar for assertion failures &lt;http://nose.readthedocs.io/en/latest/plugins/failuredetail.html&gt;`_.* IPython has something similar (`ultratb &lt;https://github.com/ipython/ipython/blob/master/IPython/core/ultratb.py&gt;`__).  Do this: ``from IPython.core import ultratb; sys.excepthook = ultratb.VerboseTB()``.  Shows more source code context (but not necessarily all relevant parts).* Ka-Ping Yee's &quot;cgitb.py&quot;, which is part of Python,  `see here &lt;https://docs.python.org/3/library/cgitb.html&gt;`__,  `code here &lt;https://github.com/python/cpython/blob/3.7/Lib/cgitb.py&gt;`__.* `Rich Python library &lt;https://github.com/willmcgugan/rich#tracebacks&gt;`__.  Syntax highlighting but without locals.* `andy-landy / traceback_with_variables &lt;https://github.com/andy-landy/traceback_with_variables&gt;`__.  Python Traceback (Error Message) Printing Variables.  Very similar, but less advanced.  Only shows locals, not globals, and also just all locals, not only those used in current statement.  Also does not expand statement if it goes over multiple lines.* `cknd / stackprinter &lt;https://github.com/cknd/stackprinter&gt;`__.  Similar as IPython ultratb.* `patrys / great-justice &lt;https://github.com/patrys/great-justice&gt;`_* See `this &lt;http://stackoverflow.com/questions/1308607/python-assert-improved-introspection-of-failure&gt;`__  related StackOverflow question.-- Albert Zeyer, &lt;http://www.az2000.de&gt;</longdescription>
</pkgmetadata>