# automatically generated by g-sorcery
# please do not edit this file

EAPI=8

REALNAME="pyams-auth-ldap"
REALVERSION="1.2.0"
DIGEST_SOURCES="yes"
PYTHON_COMPAT=( python{3_9,3_10,3_11} )
DISTUTILS_USE_PEP517=standalone

inherit python-r1 gs-pypi

DESCRIPTION="PyAMS security plug-in for LDAP authentication"

HOMEPAGE="https://pyams.readthedocs.io"
LICENSE="ZPL"
SRC_URI="https://files.pythonhosted.org/packages/e4/73/6df9fe3b1464a862a9a763eed4df2bdf40111ce414bec989fe4a43f024bd/pyams_auth_ldap-${REALVERSION}.tar.gz"
SOURCEFILE="pyams_auth_ldap-${REALVERSION}.tar.gz"
RESTRICT="test"

SLOT="0"
KEYWORDS="~amd64 ~x86"

IUSE="test"
DEPENDENCIES="dev-python/setuptools[${PYTHON_USEDEP}]
	dev-python/ldap3[${PYTHON_USEDEP}]
	dev-python/pyams-security[${PYTHON_USEDEP}]
	dev-python/pyams-utils[${PYTHON_USEDEP}]
	dev-python/pyramid[${PYTHON_USEDEP}]
	test? ( dev-python/pyams-catalog[${PYTHON_USEDEP}] )
	test? ( dev-python/pyams-security-views[${PYTHON_USEDEP}] )
	test? ( dev-python/pyams-zmi[${PYTHON_USEDEP}] )
	test? ( dev-python/pyramid-zcml[${PYTHON_USEDEP}] )
	test? ( dev-python/zope-exceptions[${PYTHON_USEDEP}] )"
BDEPEND="${DEPENDENCIES}"
RDEPEND="${DEPENDENCIES}"
