<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="person">
		<email>gentoo@houseofsuns.org</email>
		<name>Markus Walter</name>
	</maintainer>
	<longdescription>PYCHEOPS========Python package for the analysis of light curves from the `ESA CHEOPS mission &lt;http://cheops.unibe.ch/&gt;`_.Use ``pip install pycheops`` to install.See `pycheops/examples/Notebooks &lt;https://github.com/pmaxted/pycheops/tree/master/pycheops/examples/Notebooks&gt;`_ for examples.For discussion and announcements, please join the `pycheops google group &lt;https://groups.google.com/forum/#!forum/pycheops&gt;`_See pycheops/docs/PyCheops_Cookbook.pdf for a guide to using pycheops.See pycheops/examples/Notebooks for Jupyter notebook that illustrate thefeatures of pycheops.See Maxted et al. 2022MNRAS.514...77M for a full description of thealgorithms and assumptions used in pycheops. Troubleshooting***************SSLCertVerificationError------------------------Try ``$ pip uninstall python-dace-client`` ``$ pip install dace-query``Installation fails with &quot;ModuleNotFoundError: No module named 'pybind11'&quot;--------------------------------------------------------------------------Run ``pip install pybind11`` then try againStarProperties(dataset.target) produces &quot;Segmentation fault: 11&quot;-----------------------------------------------------------------You are running the wrong version of python, e.g., anaconda2 instead of anaconda3&quot;TypeError: 'str' object is not callable&quot; in animate frames ------------------------------------------------------------Install &quot;pillow&quot;, e.g., conda install pillow.&quot;No matching distribution found for matplotlib&gt;3,2 (from pycheops)&quot; -------------------------------------------------------------------- This error message may appear when upgrading to pycheops version 0.8.0 or later.  Two solutions have been found ... 1. &quot;conda update --all&quot; then &quot;pip install pycheops --upgrade&quot; 2. &quot;pip install matplotlib --upgrade&quot; then &quot;pip install pycheops --upgrade&quot;Installation fails with &quot;ERROR: Could not build wheels for celerite2 which use PEP 517 and cannot be installed directly&quot; ------------------------------------------------------------------------------------------------------------------------- This error message may appear when upgrading to pycheops version 0.9.1 or later. The working solution is to install celerite2 prior to installing/ updating pycheops using: ``git clone --recursive https://github.com/dfm/celerite2.git`` ``cd celerite2`` ``python -m pip install celerite2==0.0.1rc1``</longdescription>
</pkgmetadata>